<style type="text/css">

    #failover {
        background-color: #FCE45C;
        padding: .3em 2em;
        text-align: center;
        border: dashed #000 1px;
    }

    #failover h2 {
      color: #000!important;
      margin: 6px;
      font-size: 18px;
    }

    #failover p {
      margin: 6px;
      font-size: 15px;
    }

    #failover a {
      text-decoration: underline!important;
    }

    @media only screen and (max-width:480px) {

    #failover p {
      font-size: .8em;
    }

    }

    </style>
   <div id="failover">
    <p>This resource has been archived but you can still access its themed content and PDF files. You can search Discovery, our online catalogue, to find the full range of records held here at The National Archives and in other UK archives.</p></div>




<div id="hdr">
	<script src="/script/jquery-latest.js" type="text/javascript"></script>
	<script src="/script/global-search.js" type="text/javascript"></script>
	<script src="/script/hdr-search-utils.js" type="text/javascript"></script>
	
	<div id="hdr-logo-holder">
	<a href="/" title="The National Archives"><img src="/images/global/hdr-logo.gif" alt="The National Archives" title="The National Archives" /></a>
	</div>
	<ul class="hidden">
		<li><a href="#content" accesskey="s">Skip to Content</a></li>
		<li><a href="/help/web-accessibility/" accesskey="0">List of Access Keys</a></li>
	</ul>

</div>
</div>
