<style type="text/css">

    #failover {
        background-color: #FCE45C;
        padding: .3em 2em;
        text-align: center;
        border: dashed #000 1px;
    }

    #failover h2 {
      color: #000!important;
      margin: 6px;
      font-size: 18px;
    }

    #failover p {
      margin: 6px;
      font-size: 15px;
    }

    #failover a {
      text-decoration: underline!important;
    }

    @media only screen and (max-width:480px) {

    #failover p {
      font-size: .8em;
    }

    }

    </style>
   <div id="failover">
    <p>This resource has been archived but you can still access its themed content and PDF files. You can search Discovery, our online catalogue, to find the full range of records held here at The National Archives and in other UK archives.</p></div>




<div id="hdr">
	<script src="/script/jquery-latest.js" type="text/javascript"></script>
	<script src="/script/global-search.js" type="text/javascript"></script>
	<script src="/script/hdr-search-utils.js" type="text/javascript"></script>
	
	<div id="hdr-logo-holder">
	<a href="/" title="The National Archives"><img src="/images/global/hdr-logo.gif" alt="The National Archives" title="The National Archives" /></a>
	</div>
	<ul class="hidden">
		<li><a href="#content" accesskey="s">Skip to Content</a></li>
		<li><a href="/help/web-accessibility/" accesskey="0">List of Access Keys</a></li>
	</ul>
<div id="searchTools">
        <div id="linksToSearchForms"><a href="/search/results">Search the website</a> | <a href="http://www.discovery.nationalarchives.gov.uk">Search the catalogue</a></div>
    <div id="tnaSearchWrapper">
        <!-- div id="userControls"><a href="/legal/cookies/">Cookie policy</a> | <div id="hdr-personalisation"><a href="/Search/Login.aspx">MyPage (not signed in)</a></div></div-->
        <div id="tnaSearchWrapperInner">   
        <form action="/search/results" method="get" id="globalSearch">
            <label for="tnaSearch">Search the archives</label>
            <span id="searchOptionToggler">Search our website</span>
            <span id="containingBox">
            <input type="text" id="tnaSearch" name="_q" required aria-required="true" />
            <input type="image" id="tnaSearchSubmit" src="/images/global/searchButtonImage.png"/>
            </span>
        </form>
        </div> 
        <div id="searchFormOptions" class="noJavaScript">
                <ul id="searchOptions">
                    <li>Search our website</li>
                    <li>Search our records</li>
                </ul>
            </div>         
    </div>
</div> 


</div>
</div>
